import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params?: Promise<{ [key: string]: string | string[] }>;
}>) {
  // #region agent log
  const resolvedParams = params ? await params : null;
  try {
    await fetch(
      "http://127.0.0.1:7242/ingest/9aa2608f-0fed-41bd-8f28-52f5913ce42c",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          location: "app/layout.tsx:21",
          message: "RootLayout entry",
          data: { hasParams: !!resolvedParams },
          sessionId: "debug-session",
          runId: "run1",
          hypothesisId: "B",
        }),
      }
    );
  } catch {
    // Ignore fetch errors
  }
  // #endregion
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
